# VGGFace2 Attribute

In [1]:
import os
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import OrderedDict
from PIL import Image
from models.AttributeNet import Bottleneck, ResNet

import matplotlib.pyplot as plt

import cv2

In [2]:
model = ResNet(Bottleneck, [3, 4, 6, 3])
pretrained = "ckpt/AttributeNet-VGGFace2.pkl"

model_dict = model.state_dict()
pretrained_param = torch.load(pretrained, map_location=torch.device('cpu'))
try:
    pretrained_param = pretrained_param.state_dict()
except:
    pass

new_state_dict = OrderedDict()
for k, v in pretrained_param.items():
    if k in model_dict:
        new_state_dict[k] = v
        print("Load parameter {}".format(k))
    elif k[7:] in model_dict:
        new_state_dict[k[7:]] = v
        print("Load parameter {}".format(k[7:]))

model_dict.update(new_state_dict)
model.load_state_dict(model_dict)
# model.cuda()
model.eval()

Load parameter conv1.weight
Load parameter bn1.weight
Load parameter bn1.bias
Load parameter bn1.running_mean
Load parameter bn1.running_var
Load parameter bn1.num_batches_tracked
Load parameter layer1.0.conv1.weight
Load parameter layer1.0.bn1.weight
Load parameter layer1.0.bn1.bias
Load parameter layer1.0.bn1.running_mean
Load parameter layer1.0.bn1.running_var
Load parameter layer1.0.bn1.num_batches_tracked
Load parameter layer1.0.conv2.weight
Load parameter layer1.0.bn2.weight
Load parameter layer1.0.bn2.bias
Load parameter layer1.0.bn2.running_mean
Load parameter layer1.0.bn2.running_var
Load parameter layer1.0.bn2.num_batches_tracked
Load parameter layer1.0.conv3.weight
Load parameter layer1.0.bn3.weight
Load parameter layer1.0.bn3.bias
Load parameter layer1.0.bn3.running_mean
Load parameter layer1.0.bn3.running_var
Load parameter layer1.0.bn3.num_batches_tracked
Load parameter layer1.0.downsample.0.weight
Load parameter layer1.0.downsample.1.weight
Load parameter layer1.0.downsa

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1

In [3]:
def Path_Image_Preprocessing(path):
    '''
    Precessing the input images
        image_dir: single image input path, such as "/home/xxx/10.jpg"
    '''
    mean_bgr = np.array([91.4953, 103.8827, 131.0912])
    image = cv2.imread(path)
    assert image is not None
    image = cv2.resize(image,(224,224))
    image = image.astype(np.float32)
    image -= mean_bgr
    # H * W * C   -->   C * H * W
    image = image.transpose(2,0,1)
    image = torch.tensor(image)
    image = image.unsqueeze(0)
    return image

In [4]:
img_path = "image/0001_01.jpg"

In [5]:
img = Path_Image_Preprocessing(img_path)

In [6]:
model.to("cuda:0")

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1

In [7]:
model(img.to("cuda:0"))

[tensor([[-3.2464,  3.2464]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[ 5.0319, -2.6858, -2.3416]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[-2.0106,  4.3319, -2.3362]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[-2.9176,  5.1455, -2.2221]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[ 3.2828, -2.8861, -0.4020]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[-4.0965,  5.1140, -0.9972]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[ 3.6238, -3.0235, -0.6040]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[-2.3789,  4.8772, -2.5455]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[-2.0208,  0.9672,  2.3222, -3.2441,  1.9985]], device='cuda:0',
        grad_fn=<AddmmBackward0>),
 tensor([[ 3.7580, -3.7579]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[-3.8646,  3.8646]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[-3.6931,  3.6932]], de

In [8]:
batch_size = 1  #批处理大小
input_shape = (3, 224, 224)   #输入数据,改成自己的输入shape

In [9]:
x = torch.randn(batch_size, *input_shape)   # 生成张量
x = x.cuda()
export_onnx_file = "ckpt/AttributeNet-VGGFace2.onnx"		# 目的ONNX文件名
torch.onnx.export(model,
                    x,
                    export_onnx_file,
                    opset_version=10,
                    do_constant_folding=True,	# 是否执行常量折叠优化
                    input_names=["input"],	# 输入名
                    output_names=["output"],	# 输出名
                    dynamic_axes={"input":{0:"batch_size"},  # 批处理变量
                                    "output":{0:"batch_size"}})

## VggFace2 Attribute ONNX

In [1]:
import onnx_tf.backend
import onnx

import numpy as np
from PIL import Image
import torchvision.transforms as transforms

import cv2

2023-04-18 20:12:02.092670: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-18 20:12:02.137522: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-18 20:12:02.866079: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/cry/anaconda3/envs/hsic/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode

In [2]:
def Path_Image_Preprocessing(path):
    '''
    Precessing the input images
        image_dir: single image input path, such as "/home/xxx/10.jpg"
    '''
    mean_bgr = np.array([91.4953, 103.8827, 131.0912])
    image = cv2.imread(path)
    assert image is not None
    image = cv2.resize(image,(224,224))
    image = image.astype(np.float32)
    image -= mean_bgr
    # H * W * C   -->   C * H * W
    image = image.transpose(2,0,1)
    image = np.array([image, image, image, image])
    return image

In [3]:
img_path = "image/0001_01.jpg"
model_path = "ckpt/AttributeNet-VGGFace2.onnx"

In [4]:
img = Path_Image_Preprocessing(img_path)

In [5]:
onnx_model = onnx.load(model_path)
tf_model = onnx_tf.backend.prepare(onnx_model, device='CPU')

2023-04-18 20:12:13.740384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21725 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:b3:00.0, compute capability: 8.6


In [6]:
result = tf_model.run(img)

2023-04-18 20:12:24.067119: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:424] Loaded cuDNN version 8600
2023-04-18 20:12:24.816126: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [21]:
np.array([
    [result[0][:,1]],
    [result[0][:,1]],
    [result[0][:,1]],
    ]).shape

(3, 1, 2)

In [7]:
x = result[0][:,1][:, np.newaxis]

In [8]:
x.shape

(4, 1)

In [42]:
np.append(x, x-1, 1)

array([[3.249253, 2.249253],
       [3.249253, 2.249253]], dtype=float32)

In [10]:
np.append(x, x-1, 1)

array([[3.249878, 2.249878],
       [3.249878, 2.249878],
       [3.249878, 2.249878],
       [3.249878, 2.249878]], dtype=float32)

: 

In [46]:
x-1

array([[2.249253],
       [2.249253]], dtype=float32)

In [49]:
out = [[] for i in range(2)]
np.array(out)

array([], shape=(2, 0), dtype=float64)

# Celeb-A AttributeNet

In [1]:
import os
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import OrderedDict
from PIL import Image
from models.BranchedTiny import BranchedTinyAttr

import matplotlib.pyplot as plt
import torchvision.transforms.functional as TF

import cv2

/home/cry/anaconda3/envs/hsic/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
attribute_net = BranchedTinyAttr()

In [3]:
def interpolate(img, size):
    if type(size) == tuple:
        assert size[0] == size[1]
        size = size[0]

    orig_size = img.size(3)
    if size < orig_size:
        mode = 'area'
    else:
        mode = 'bilinear'
    return F.interpolate(img, (size, size), mode=mode)

def read_img(path):
    img = Image.open(path).convert('RGB')
    img = TF.to_tensor(img)
    img = img.unsqueeze(0)
    if img.size(-1) != 224:
        img = interpolate(img, 224)
    return img

In [4]:
img_path = "image/n000002-0001_01.jpg"

In [5]:
attribute_net.set_idx_list(['male', 'young',
    'arched_eyebrows', 'bushy_eyebrows',
    'mouth_slightly_open', 'big_lips',
    'big_nose', 'pointy_nose',
    'bags_under_eyes', 'narrow_eyes'])

In [6]:
input_data = read_img(img_path)
predicted = attribute_net(input_data)

In [7]:
predicted 

tensor([[-4.9536,  4.8605, -0.7729, -3.5993, -1.5853, -1.6258, -4.3598, -1.3096,
         -3.4509, -3.9110]], grad_fn=<IndexBackward0>)

In [8]:
batch_size = 1  #批处理大小
input_shape = (3, 224, 224)   #输入数据,改成自己的输入shape

In [9]:
x = torch.randn(batch_size, *input_shape)   # 生成张量
x = x.cuda()
export_onnx_file = "ckpt/AttributeNet-CelebA.onnx"		# 目的ONNX文件名
torch.onnx.export(attribute_net.cuda(),
                    x,
                    export_onnx_file,
                    opset_version=10,
                    do_constant_folding=True,	# 是否执行常量折叠优化
                    input_names=["input"],	# 输入名
                    output_names=["output"],	# 输出名
                    dynamic_axes={"input":{0:"batch_size"},  # 批处理变量
                                    "output":{0:"batch_size"}})

## Celeb-A Attribute ONNX

In [6]:
import onnx_tf.backend
import onnx

import numpy as np
from PIL import Image
import torchvision.transforms.functional as TF
import torch.nn.functional as F

import cv2

In [2]:
def interpolate(img, size):
    if type(size) == tuple:
        assert size[0] == size[1]
        size = size[0]

    orig_size = img.size(3)
    if size < orig_size:
        mode = 'area'
    else:
        mode = 'bilinear'
    return F.interpolate(img, (size, size), mode=mode)

def read_img(path):
    img = Image.open(path).convert('RGB')
    img = TF.to_tensor(img)
    img = img.unsqueeze(0)
    if img.size(-1) != 224:
        img = interpolate(img, 224)
    return img.numpy()

In [3]:
img_path = "image/n000002-0001_01.jpg"
model_path = "ckpt/AttributeNet-CelebA.onnx"

In [4]:
onnx_model = onnx.load(model_path)
tf_model = onnx_tf.backend.prepare(onnx_model, device='CPU')

2023-04-24 15:51:26.476769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21761 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:b3:00.0, compute capability: 8.6


In [7]:
img = read_img(img_path)

In [12]:
result = tf_model.run(np.array([img[0], img[0]]))

In [32]:
np.append(result[0][:,1][:, np.newaxis],
          result[0][:,1][:, np.newaxis] -1, 1
          )

array([[4.860705, 3.860705],
       [4.860705, 3.860705]], dtype=float32)